nohup: ignoring input
Traceback (most recent call last):
  File "/home/qj2004/GraphSHA/DiGMain.py", line 327, in <module>
    val_loss = train(train_idx, edge_in, in_weight, edge_out, out_weight, SparseEdges, edge_weight)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/GraphSHA/DiGMain.py", line 127, in train
    out = model(new_x, new_SparseEdges, edge_weight)  # all data+ aug
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: APPNP_ModelBen.forward() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "/home/qj2004/GraphSHA/DiGMain.py", line 327, in <module>
    val_loss = train(train_idx, edge_in, in_weight, edge_out, out_weight, SparseEdges, edge_weight)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/GraphSHA/DiGMain.py", line 127, in train
    out = model(new_x, new_SparseEdges, edge_weight)  # all data+ aug
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: APPNP_ModelBen.forward() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "/home/qj2004/GraphSHA/DiGMain.py", line 327, in <module>
    val_loss = train(train_idx, edge_in, in_weight, edge_out, out_weight, SparseEdges, edge_weight)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/GraphSHA/DiGMain.py", line 127, in train
    out = model(new_x, new_SparseEdges, edge_weight)  # all data+ aug
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: APPNP_ModelBen.forward() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "/home/qj2004/GraphSHA/DiGMain.py", line 327, in <module>
    val_loss = train(train_idx, edge_in, in_weight, edge_out, out_weight, SparseEdges, edge_weight)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/GraphSHA/DiGMain.py", line 127, in train
    out = model(new_x, new_SparseEdges, edge_weight)  # all data+ aug
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: APPNP_ModelBen.forward() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "/home/qj2004/GraphSHA/DiGMain.py", line 327, in <module>
    val_loss = train(train_idx, edge_in, in_weight, edge_out, out_weight, SparseEdges, edge_weight)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/GraphSHA/DiGMain.py", line 127, in train
    out = model(new_x, new_SparseEdges, edge_weight)  # all data+ aug
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: APPNP_ModelBen.forward() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "/home/qj2004/GraphSHA/DiGMain.py", line 327, in <module>
    val_loss = train(train_idx, edge_in, in_weight, edge_out, out_weight, SparseEdges, edge_weight)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/GraphSHA/DiGMain.py", line 127, in train
    out = model(new_x, new_SparseEdges, edge_weight)  # all data+ aug
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: APPNP_ModelBen.forward() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "/home/qj2004/GraphSHA/DiGMain.py", line 327, in <module>
    val_loss = train(train_idx, edge_in, in_weight, edge_out, out_weight, SparseEdges, edge_weight)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/GraphSHA/DiGMain.py", line 127, in train
    out = model(new_x, new_SparseEdges, edge_weight)  # all data+ aug
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: APPNP_ModelBen.forward() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "/home/qj2004/GraphSHA/DiGMain.py", line 327, in <module>
    val_loss = train(train_idx, edge_in, in_weight, edge_out, out_weight, SparseEdges, edge_weight)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/GraphSHA/DiGMain.py", line 127, in train
    out = model(new_x, new_SparseEdges, edge_weight)  # all data+ aug
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: APPNP_ModelBen.forward() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "/home/qj2004/GraphSHA/DiGMain.py", line 327, in <module>
    val_loss = train(train_idx, edge_in, in_weight, edge_out, out_weight, SparseEdges, edge_weight)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/GraphSHA/DiGMain.py", line 127, in train
    out = model(new_x, new_SparseEdges, edge_weight)  # all data+ aug
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: APPNP_ModelBen.forward() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "/home/qj2004/GraphSHA/DiGMain.py", line 327, in <module>
    val_loss = train(train_idx, edge_in, in_weight, edge_out, out_weight, SparseEdges, edge_weight)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/GraphSHA/DiGMain.py", line 127, in train
    out = model(new_x, new_SparseEdges, edge_weight)  # all data+ aug
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: APPNP_ModelBen.forward() takes 3 positional arguments but 4 were given
